
version: '3.9'

volumes:
    v_data:

services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Qwer!234"
      PGDATA: /data
    volumes:
      - v_data:/data

  backend:
    build: .
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        ./manage.py migrate
        ./manage.py runserver 0.0.0.0:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Qwer!234"
      ALLOWED_HOST: backend
      LOG_FILE_NAME: "/app/shop.log"
      PYTHONUNBUFFERED: 1
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - '80:80'
    depends_on:
      - backend
