
version: '3.9'

volumes:
    v_data:
    v_cache:

services:
  db:
    image: postgres:16.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Qwer!234"
      PGDATA: /data
    volumes:
      - v_data:/data

  redis:
    image: redis:7.2.3-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - v_cache:/data

  worker:
    build: .
    restart: always
    command: /usr/local/bin/celery -A control worker -l INFO
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Qwer!234"
      ALLOWED_HOST: backend
      LOG_FILE_NAME: "/app/shop.log"
      PYTHONUNBUFFERED: 1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - redis

  backend:
    build: .
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        ./manage.py migrate
        ./manage.py runserver 0.0.0.0:80
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Qwer!234"
      ALLOWED_HOST: backend
      LOG_FILE_NAME: "/app/shop.log"
      PYTHONUNBUFFERED: 1
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db

  web:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - '80:80'
    depends_on:
      - backend
