# Generated by Django 4.2.6 on 2023-11-02 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.contact",
                verbose_name="контакт",
            ),
            preserve_default=False,
        ),
    ]
