# Generated by Django 4.2.6 on 2023-11-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_order_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="backend.contact",
                verbose_name="контакт",
            ),
        ),
    ]
