# Generated by Django 4.2.6 on 2023-10-30 21:53

from django.db import migrations
import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_alter_user_managers_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", shop.models.UserManager()),
            ],
        ),
    ]
